# Default values for odl.
# This is a YAML-formatted file.
# Declare name/values to be passed into your templates.
# name: value


images:
  tags:
    odl: docker.io/sapan2211/odl-karaf-boron:full
  pull_policy: "IfNotPresent"

network:
  node_port:
    enabled: true
    dashboard: 8181
  cluster_ip:
    enabled: true
    manager: 6640
    controller1: 6653
    controller2: 6633
    odl_neutron_rest: 8080
  port:
    manager: 6640
    controller1: 6653
    controller2: 6633
    odl_neutron_rest: 8080
    dashboard: 8181

labels:
pod:
  replicas:
    controller: 1
  mounts:
    odl:
      init_container: null
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
        odl:
          enabled: false
          min_ready_seconds: 0
          max_unavailable: 1
  resources:
    enabled: true
    controller:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "4096Mi"
        cpu: "2000m"
manifests:
  deployment: true
  service:
    ovs: true
    dashboard: true

endpoints:
  odl:
    name: odl
    hosts:
      default: odl
      public: odl
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
  dashboard:
    name: odl-dashboard
    hosts:
      default: odl-dashboard
      public: odl-dashboard
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
